export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const DELETE_FROM_BASKET = "DELETE_FROM_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";
//auth and autoriz action Types
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//category types
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_LOADED = 'CATEGORY_LOADED';
export const ADD_TO_CATEGORY = "ADD_TO_CATEGORY";
export const DELETE_FROM_CATEGORY = "DELETE_FROM_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
//product types
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_FROM_PRODUCT = "DELETE_FROM_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
//iniatial Data types
export const INITIALDATA_LOADING = 'INITIALDATA_LOADING';
export const INITIALDATA_LOADED = 'INITIALDATA_LOADED';
export const INITIALDATA_ERROR = 'INITIALDATA_ERROR';